### ISSUE TITLE
App code fail

### ISSUE THREAD

**Issue by ezraholm50** [owncloud/files_antivirus#101]
@VicDeo 

Removed old version of files_antivirus (disabled first), downloaded your fresh signed version, enabled it and rescanned the appcode in OC admin panel, checker still gives the error.

Non valid list (dont know the exact translation)
Note that anti_virus is gone but error still persist.

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => 8d335327648f2124a9d3c1d03ed775c930ecfa2deeaf732cb131c5b32f62ad05fbfd4280cdef22868b0e11db4975f0448335d50a8a4e8069a78b4f5ddfa7eb49
                        )

                )

        )

)
```

Occ code checker:
```
root@owncloud:/var/www/owncloud# sudo -u www-data php occ app:check-code files_antivirus
Analysing /var/www/owncloud/apps/files_antivirus/appinfo/preupdate.php
 4 errors
    line    3: OCP\Config - Static method of deprecated class must not be called
    line    5: OCP\DB - Static method of deprecated class must not be called
    line    8: OCP\DB - Static method of deprecated class must not be called
    line   13: OCP\DB - Static method of deprecated class must not be called
Analysing /var/www/owncloud/apps/files_antivirus/appinfo/app.php
 3 errors
    line   25: OCP\BackgroundJob::AddRegularTask - Method of deprecated class must not be called
    line   37: OCP\Config - Static method of deprecated class must not be called
    line   45: OCP\Config - Static method of deprecated class must not be called
Analysing /var/www/owncloud/apps/files_antivirus/appinfo/update.php
 2 errors
    line   10: OCP\Config - Static method of deprecated class must not be called
    line   24: == - is discouraged
Analysing /var/www/owncloud/apps/files_antivirus/lib/backgroundscanner.php
 6 errors
    line   64: OCP\DB - Static method of deprecated class must not be called
    line   67: OCP\DB - Static method of deprecated class must not be called
    line   68: OCP\DB - Static method of deprecated class must not be called
    line   86: OC_Util - Static method of private class must not be called
    line  100: OC_Util - Static method of private class must not be called
    line  101: OC_Util - Static method of private class must not be called
Analysing /var/www/owncloud/apps/files_antivirus/lib/item.php
 7 errors
    line  156: OCP\JSON - Static method of deprecated class must not be called
    line  181: OCP\DB - Static method of deprecated class must not be called
    line  183: OCP\DB - Static method of deprecated class must not be called
    line  185: OCP\DB - Static method of deprecated class must not be called
    line  187: OCP\DB - Static method of deprecated class must not be called
    line  189: OCP\DB - Static method of deprecated class must not be called
    line  190: OCP\DB - Static method of deprecated class must not be called
Analysing /var/www/owncloud/apps/files_antivirus/lib/notification.php
 9 errors
    line   16: OCP\Config - Static method of deprecated class must not be called
    line   16: OCP\User::getUser - Method of deprecated class must not be called
    line   18: OCP\Config - Static method of deprecated class must not be called
    line   18: OCP\User::getUser - Method of deprecated class must not be called
    line   20: OCP\User::getUser - Method of deprecated class must not be called
    line   24: OCP\User::getUser - Method of deprecated class must not be called
    line   31: OCP\Util::getServerHost - Method of deprecated class must not be called
    line   32: OCP\User::getDisplayName - Method of deprecated class must not be called
    line   35: OCP\Util::sendMail - Method of deprecated class must not be called
Analysing /var/www/owncloud/apps/files_antivirus/lib/avirwrapper.php
 1 errors
    line   73: == - is discouraged
Analysing /var/www/owncloud/apps/files_antivirus/lib/status.php
 1 errors
    line   81: == - is discouraged
Duplicate min ownCloud version requirement found
Deprecated field available: requiremin => 8
App is not compliant

```

OC Log:

```
Error	core	Error while running background job (class: OC\BackgroundJob\Legacy\RegularJob, arguments: Array ( [0] => OCA\Files_Antivirus\Cron\Task [1] => run ) ): {"Exception":"OCP\\Files\\NotFoundException","Message":"File with id \"3227\" has not been found.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_antivirus\/lib\/backgroundscanner.php(78): OC\\Files\\View->getPath(3227)\n#1 \/var\/www\/owncloud\/apps\/files_antivirus\/lib\/cron\/task.php(21): OCA\\Files_Antivirus\\BackgroundScanner->run()\n#2 [internal function]: OCA\\Files_Antivirus\\Cron\\Task::run()\n#3 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/legacy\/regularjob.php(28): call_user_func(Array)\n#4 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OC\\BackgroundJob\\Legacy\\RegularJob->run(Array)\n#5 \/var\/www\/owncloud\/cron.php(141): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#6 {main}","File":"\/var\/www\/owncloud\/lib\/private\/files\/view.php","Line":1639}	2 minutes ago
Error	PHP	array_map(): Argument #2 should be an array at /var/www/owncloud/lib/private/group/manager.php#283	2 minutes ago
Error	PHP	array_keys() expects parameter 1 to be array, boolean given at /var/www/owncloud/lib/private/group/manager.php#283
```

I'm lost here, please shine a light on this darkness?!

Kind regards,

Ezra

**Comment by VicDeo** [comment]
@ezraholm50 
>- core
    - INVALID_HASH
        - .htaccess

is from core
https://github.com/owncloud/core/issues/22966
https://github.com/owncloud/core/issues/22982

everything else belongs to this repo

**Comment by ezraholm50** [comment]
Thanks, hope the occ check is usefull for you. The oc log showing that error, might be worth investigating the database as someone stated before within the issues of this repo?
