### ISSUE TITLE
Antivirus app prevents upload from official Owncloud Android client app > 1MiB

### ISSUE THREAD

**Issue by e-alfred** [owncloud/files_antivirus#110]
### Steps to reproduce
1. Install and activate antivirus app in Owncloud
2. Upload file bigger than 1MiB using the official Android Owncloud app
### Expected behaviour

The selected file should be uploaded and scanned from the Android phone to Owncloud.
### Actual behaviour

The upload fails after some chunk is scanned by the Antivirus app/Clamav. If I disable the Antivirus app everything works fine.
### Server configuration

**Operating system**: Ubuntu 14.04.5 Server

**Web server:** Apache 2.4.7

**Database:** 5.5.49

**PHP version:** 5.5.9

**ownCloud version:** 8.2.3

**Updated from an older ownCloud or fresh install:** 8.1

**Where did you install ownCloud from:** Owncloud deb repository

**List of activated apps:**

```
Enabled:
  - activity: 2.1.4
  - bookmarks: 0.7.1
  - calendar: 0.8.2
  - checksum: 2.0
  - contacts: 0.5.0.0
  - documents: 0.11.1
  - external: 1.2
  - files: 1.2.1
  - files_clipboard: 0.4.2
  - files_epubviewer: 7.0.5
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_reader: 0.7.1
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - flowupload: 0.2
  - gallery: 14.2.0
  - html5_videoplayer: 1.0
  - imprint: 0.2.5
  - maps: 0.0.6
  - music: 0.3.11
  - news: 7.1.2
  - notifications: 0.1.0
  - ocdownloader: 1.5
  - ownbackup: 0.3.8
  - ownnote: 1.07
  - passwords: 18.0
  - pinit: 1.0.1
  - provisioning_api: 0.3.0
  - rainloop: 4.9
  - search_lucene: 0.7.0
  - secure_container: 0.0.6
  - sharelinks: 1.1.0
  - sketch: 0.1.2
  - tasks: 0.8.1
  - templateeditor: 0.1
  - weather: 1.3.1
  - files_antivirus 0.8.0.1
Disabled:
  - encryption
  - ojsxc
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocb9d94613a4",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "8.2.3.2",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": true,
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "filesystem_check_changes": 1,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "loglevel": 0,
        "logtimezone": "Europe\/Vienna",
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using encryption:** no
### Client configuration

**Browser:** Owncloud Android App 1.9.1

**Operating system:** Android 6.0
#### Owncloud server log

```
{"reqId":"Vx1CdH8AAQEAAFWMwccAAAAF","remoteAddr":"1.2.3.4","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-04-25T00:02:29+02:00","method":"HEAD","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/"}
{"reqId":"Vx1CdX8AAQEAAFWMwcgAAAAF","remoteAddr":"1.2.3.4","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name SofortUpload\\\/IMG_20160424_120630.jpg could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(78): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('SofortUpload\\\/IM...', 0)\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":159}","level":0,"time":"2016-04-25T00:02:29+02:00","method":"HEAD","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20160424_120630.jpg"}
{"reqId":"Vx1CdX8AAQEAAFWMwckAAAAF","remoteAddr":"1.2.3.4","app":"files_antivirus","message":"Exit code :: 0 Response :: stdin: OK\n\n----------- SCAN SUMMARY -----------\nKnown viruses: 4300043\nEngine version: 0.98.7\nScanned directories: 0\nScanned files: 1\nInfected files: 0\nData scanned: 0.98 MB\nData read: 0.98 MB (ratio 1.01:1)\nTime: 10.368 sec (0 m 10 s)\n","level":0,"time":"2016-04-25T00:02:40+02:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20160424_120630.jpg-chunking-6189-5-0"}
{"reqId":"Vx1CdX8AAQEAAFWMwckAAAAF","remoteAddr":"1.2.3.4","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 1024000 got 0\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(101): OC\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #57)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(115): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #57)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('IMG_20160424_12...', Resource id #57)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('SofortUpload\\\/IM...', Resource id #57, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":381}","level":4,"time":"2016-04-25T00:02:40+02:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20160424_120630.jpg-chunking-6189-5-0"}
{"reqId":"Vx1CgH8AAQEAAFWegdMAAAAC","remoteAddr":"1.2.3.4","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:70) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-04-25T00:02:40+02:00","method":"HEAD","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/"}
{"reqId":"Vx1CgH8AAQEAAFWegdQAAAAC","remoteAddr":"1.2.3.4","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name SofortUpload\\\/IMG_20160424_120616.jpg could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(78): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('SofortUpload\\\/IM...', 0)\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":159}","level":0,"time":"2016-04-25T00:02:40+02:00","method":"HEAD","url":"\/owncloud\/remote.php\/webdav\/SofortUpload\/IMG_20160424_120616.jpg"}
```

**Comment by hitam4450** [comment]
Same problem with me...uploads always got stuck at 57 % ! After disabling the antivirus app...everything works fine!

**Comment by VicDeo** [comment]
@e-alfred is it still reproducible with newer versions?

**Comment by patrickjahns** [comment]
closing - if this issue still occurs - please reopen a new ticket
