### ISSUE TITLE
Updating AV ruleset fails on both OC9 and 10 (oracle DB)

### ISSUE THREAD

**Issue by Emil-G** [owncloud/files_antivirus#164]
Hi,

When attempting to update the AV ruleset (Oracle DB backend) error messages are printed to the owncloud log, and no change is committed.

1: Do a change on the ruleset.
2: Press the checkmark buttion and see error in log: ![image](https://user-images.githubusercontent.com/402551/28111033-67538e4a-66f4-11e7-83b0-18e4fa3bf56b.png)
3: When refreshing page, no change has been committed. 

Tested on both OC 9.1.6 and 10.0.2

OC 10.0.2 error message:
```
{"reqId":"WWXpskpIWoTZzyWmfJRtawAAAAQ","level":3,"time":"2017-07-12T11:19:47+02:00","remoteAddr":"10.248.28.207","user":"Admin","app":"index","method":"POST","url":"/index.php/apps/files_antivirus/settings/rule/save","message":"Exception: {\"Exception\":\"Doctrine\DBAL\Exception\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM oc_files_avir_status WHERE id = ?' with params [76]:\n\nORA-00942: tabellen eller utsnittet finnes ikke\",\"Code\":0,\"Trace\":\"
#0 /var/www/html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception))
#1 /var/www/html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(177): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\OCI8\Driver), Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception), 'SELECT * FROM o...', Array)
#2 /var/www/html/owncloud/lib/private/legacy/db/statementwrapper.php(71): Doctrine\DBAL\Statement->execute()
#3 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(252): OC_DB_StatementWrapper->execute()
#4 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(285): OCP\AppFramework\Db\Mapper->execute('SELECT * FROM *...', Array, NULL, NULL)
#5 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(379): OCP\AppFramework\Db\Mapper->findOneQuery('SELECT * FROM *...', Array, NULL, NULL)
#6 /var/www/html/owncloud/apps/files_antivirus/lib/db/rulemapper.php(37): OCP\AppFramework\Db\Mapper->findEntity('SELECT * FROM *...', Array)
#7 /var/www/html/owncloud/apps/files_antivirus/controller/rulecontroller.php(71): OCA\Files_Antivirus\Db\RuleMapper->find(76)
#8 [internal function]: OCA\Files_Antivirus\Controller\RuleController->save(76, 2, '/.*: OK$/', 'testing', 0)
#9 /var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
#10 /var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_Antivirus\Controller\RuleController), 'save')
#11 /var/www/html/owncloud/lib/private/AppFramework/App.php(98): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_Antivirus\Controller\RuleController), 'save')
#12 /var/www/html/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('RuleController', 'save', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#13 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#14 /var/www/html/owncloud/lib/private/Route/Router.php(299): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#15 /var/www/html/owncloud/lib/base.php(918): OC\Route\Router->match('/apps/files_ant...')
#16 /var/www/html/owncloud/index.php(49): OC::handleRequest()
#17 {main}\",\"File\":\"/var/www/html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php\",\"Line\":58}"}
```

OC 9.1.6 error message:
```
{"reqId":"WWXraa3f6dNr3OvSxxICngAAAB4","remoteAddr":"10.248.24.211","app":"index","message":"Exception: {\"Exception\":\"Doctrine\DBAL\Exception\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM oc_files_avir_status WHERE id = ?' with params [17]:\n\nORA-00942: tabellen eller utsnittet finnes ikke\",\"Code\":0,\"Trace\":\"
#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception))
#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(175): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\OCI8\Driver), Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception), 'SELECT * FROM o...', Array)
#2 /var/www/html/owncloud/lib/private/legacy/db/statementwrapper.php(75): Doctrine\DBAL\Statement->execute()
#3 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(251): OC_DB_StatementWrapper->execute()
#4 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(280): OCP\AppFramework\Db\Mapper->execute('SELECT * FROM *...', Array, NULL, NULL)
#5 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(372): OCP\AppFramework\Db\Mapper->findOneQuery('SELECT * FROM *...', Array, NULL, NULL)
#6 /var/www/html/owncloud/apps/files_antivirus/lib/db/rulemapper.php(37): OCP\AppFramework\Db\Mapper->findEntity('SELECT * FROM *...', Array)
#7 /var/www/html/owncloud/apps/files_antivirus/controller/rulecontroller.php(71): OCA\Files_Antivirus\Db\RuleMapper->find(17)
#8 [internal function]: OCA\Files_Antivirus\Controller\RuleController->save(17, 2, '/.*: OK$/', 'test', 0)
#9 /var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
#10 /var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_Antivirus\Controller\RuleController), 'save')
#11 /var/www/html/owncloud/lib/private/AppFramework/App.php(99): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_Antivirus\Controller\RuleController), 'save')
#12 /var/www/html/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('RuleController', 'save', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#13 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#14 /var/www/html/owncloud/lib/private/Route/Router.php(280): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#15 /var/www/html/owncloud/lib/base.php(891): OC\Route\Router->match('/apps/files_ant...')
#16 /var/www/html/owncloud/index.php(54): OC::handleRequest()
#17 {main}\",\"File\":\"/var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php\",\"Line\":58}","level":3,"time":"2017-07-12T11:27:06+02:00","method":"POST","url":"/index.php/apps/files_antivirus/settings/rule/save","user":"emigol"}
```

**Comment by michaelstingl** [comment]
@PVince81 I need an assignment here.

00007924

**Comment by PVince81** [comment]
@VicDeo

**Comment by Emil-G** [comment]
I am not sure if it is related, but I do see these errors in OC10 as well (oracle DB error message) related to the _BackgroundScanner_:
```
{"reqId":"4m6TUyy2Nnk3kjW108LY","level":3,"time":"2017-07-13T08:15:01+02:00","remoteAddr":"","user":"--","app":"files_antivirus","method":"--","url":"--","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: An exception occurred while executing 'SELECT fc.\"fileid, mnt.user_id\" FROM \"oc_filecache\" fc LEFT JOIN \"oc_files_antivirus\" fa ON fa.\"fileid\" = fc.\"fileid\" INNER JOIN \"oc_mounts\" mnt ON (fc.\"storage\" = mnt.\"storage_id\") AND (mnt.\"mount_point\" = '\/' || mnt.\"user_id\" || '\/')) WHERE (fc.\"mimetype\" <> '2') AND ((fa.\"fileid\" IS NULL) OR (fc.\"mtime\" > fa.\"check_time\")) AND (fc.\"path\" LIKE 'files\/%') AND ((fc.\"size\" <> '0') AND (fc.\"size\" < '50000000'))':\n\nORA-00933: SQL-kommandoen er ikke avsluttet riktig"}
```

**Comment by VicDeo** [comment]
@Emil-G what is exact Oracle version?
I have the following with 11.2.0.2.0:
```
SQL> SELECT table_name FROM user_tables where table_name like '%avir%';

TABLE_NAME
------------------------------
files_avir_status
```

and then

```
SQL> SELECT * FROM files_avir_status;
SELECT * FROM files_avir_status
              *
ERROR at line 1:
ORA-00942: table or view does not exist
```

Google tells me that it could be a known bug of 11.2 https://stackoverflow.com/questions/29654867/ora-00942-but-the-table-exists-in-dba-tables-and-dba-objects

**Comment by Emil-G** [comment]
@VicDeo : We are using **Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production**. Using the latest instaclient (oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64).
Cheers,
Emil

**Comment by VicDeo** [comment]
@Emil-G 
 >I do see these errors in OC10 as well (oracle DB error message) related to the BackgroundScanner.

Please use 1 issue per report. Bg job issues are already  addressed in https://github.com/owncloud/files_antivirus/pull/162

**Comment by Emil-G** [comment]
Closing, as was fixed in [167](https://github.com/owncloud/files_antivirus/pull/167).

**Comment by michaelstingl** [comment]
@Emil-G https://github.com/owncloud/files_antivirus/pull/167 hasn't been merged yet. (needs unit tests too)

**Comment by Emil-G** [comment]
@michaelstingl : hi, this change is in the changelog for enterprise 10.0.3. But it is actually not included in the 10.0.3 enterprise release. 

Readme from tarball says:
### Fixed
- Oracle: Error when saving a rule  [167](https://github.com/owncloud/files_antivirus/pull/167)

But the line is still the old, non functioning one.

**Comment by michaelstingl** [comment]
@Emil-G Thank you very much for your feedback!

@VicDeo @PVince81 Please check

**Comment by PVince81** [comment]
Checked, missing backport: https://github.com/owncloud/files_antivirus/pull/167#issuecomment-331160574

**Comment by VicDeo** [comment]
Backport arrived https://github.com/owncloud/files_antivirus/pull/188

**Comment by michaelstingl** [comment]
@Emil-G files_antivirus 0.11.2 has been released, and can be downloaded from ownCloud Marketplace, including the fix for this issue:
https://marketplace.owncloud.com/apps/files_antivirus
