### ISSUE TITLE
exception shown in the log when using async upload

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#275]
when the async move (https://github.com/owncloud/core/pull/32414) is used to upload a virus file a exception is shown in the log, a normal MOVE does not produce that exception,  but only the message that the infected file is deleted.
is this a bug or a feature?
```
{"reqId":"rx5FLSG9yXh6dRm2AyLn","level":2,"time":"2018-11-26T05:51:15+00:00","remoteAddr":"192.168.1.6","user":"user0","app":"files_antivirus","method":"MOVE","url":"\/owncloud-core\/remote.php\/dav\/uploads\/user0\/chunking-42\/.file","message":"Infected file deleted. Eicar-Test-Signature Account: user0 Path: files\/myChunkedFile.txt.ocTransferId560398872.part"}
{"reqId":"rx5FLSG9yXh6dRm2AyLn","level":3,"time":"2018-11-26T05:51:15+00:00","remoteAddr":"192.168.1.6","user":"user0","app":"no app in context","method":"MOVE","url":"\/owncloud-core\/remote.php\/dav\/uploads\/user0\/chunking-42\/.file","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"Virus Eicar-Test-Signature is detected in the file. Upload cannot be completed.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(234): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(OCP\\\\Files\\\\FileContentNotAllowedException))\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(172): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #74)\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(311): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('myChunkedFile.t...', Resource id #74)\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(135): Sabre\\\\DAV\\\\Tree->copyNode(Object(OCA\\\\DAV\\\\Upload\\\\FutureFile), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory), 'myChunkedFile.t...')\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(167): Sabre\\\\DAV\\\\Tree->copy('uploads\\\/user0\\\/c...', 'files\\\/user0\\\/myC...')\\n#5 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(641): Sabre\\\\DAV\\\\Tree->move('uploads\\\/user0\\\/c...', 'files\\\/user0\\\/myC...')\\n#6 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/DAV\\\/LazyOpsPlugin.php(124): Sabre\\\\DAV\\\\Server->emit('method:MOVE', Array)\\n#8 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/DAV\\\/LazyOpsPlugin.php(106): OCA\\\\DAV\\\\DAV\\\\LazyOpsPlugin->afterResponse(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Shutdown\\\/ShutDownManager.php(61): OCA\\\\DAV\\\\DAV\\\\LazyOpsPlugin->OCA\\\\DAV\\\\DAV\\\\{closure}()\\n#10 [internal function]: OC\\\\Shutdown\\\\ShutDownManager->run()\\n#11 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":653}"}

**Comment by DeepDiver1975** [comment]
The warning is written only if data is going through the storage wrapper - meaning when data is really copied between storages.
Chunked upload is concatenating chunks into the final file which is basically streaming data -> triggers av.

On a regular MOVE files/folders are renamed and no data is streamed around -> av is not triggered
