### ISSUE TITLE
Acceptance test antivirusFileSize.feature:45 is failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_antivirus#295]
See https://drone.owncloud.com/owncloud/files_antivirus/550/262
```
--- Failed scenarios:

    /var/www/owncloud/apps/files_antivirus/tests/acceptance/features/apiAntivirus/antivirusFileSize.feature:45

26 scenarios (25 passed, 1 failed)
255 steps (253 passed, 1 failed, 1 skipped)
6m25.51s (16.13Mb)
```
and
```
  Scenario: Files smaller than the upload threshold are checked for viruses when using chunking (use async move to upload)           # /var/www/owncloud/apps/files_antivirus/tests/acceptance/features/apiAntivirus/antivirusFileSize.feature:45
    Given parameter "av_max_file_size" of app "files_antivirus" has been set to "100"                                                # FeatureContext::serverParameterHasBeenSetTo()
    And using new DAV path                                                                                                           # FeatureContext::usingOldOrNewDavPath()
    And the administrator has enabled async operations                                                                               # FeatureContext::triggerAsyncUpload()
    When user "user0" uploads the following chunks asynchronously to "/myChunkedFile.txt" with new chunking and using the WebDAV API # FeatureContext::userUploadsTheFollowingChunksUsingNewChunking()
      | 1 | X5O!P%@AP[4\PZX54(P^)7C |
      | 2 | C)7}$EICAR-STANDARD-ANT |
      | 3 | IVIRUS-TEST-FILE!$H+H*  |
    Then the HTTP status code should be "202"                                                                                        # FeatureContext::theHTTPStatusCodeShouldBe()
    And the oc job status values of last request for user "user0" should match these regular expressions                             # FeatureContext::jobStatusValuesShouldMatchRegEx()
      | status | /^error$/ |
    And the last lines of the log file should contain log-entries containing these attributes:                                       # AntivirusContext::theLastLinesOfTheLogFileShouldContainEntriesWithTheseAttributes()
      | user  | app               | message               |
      | user0 | files_antivirus   | Infected file deleted |
      | user0 | no app in context | Exception             |
      log entry:
      {"reqId":"L3KQfVwzv2l1rZabdJDb","level":3,"time":"2019-02-14T23:42:55+00:00","remoteAddr":"172.23.0.6","user":"user0","app":"no app in context","method":"MOVE","url":"\/remote.php\/dav\/uploads\/user0\/chunking-42\/.file","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"Virus Eicar-Test-Signature is detected in the file. Upload cannot be completed.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(235): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(OCP\\\\Files\\\\FileContentNotAllowedException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(171): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #43)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(311): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('myChunkedFile.t...', Resource id #43)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(135): Sabre\\\\DAV\\\\Tree->copyNode(Object(OCA\\\\DAV\\\\Upload\\\\FutureFile), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory), 'myChunkedFile.t...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(167): Sabre\\\\DAV\\\\Tree->copy('uploads\\\/user0\\\/c...', 'files\\\/user0\\\/myC...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(641): Sabre\\\\DAV\\\\Tree->move('uploads\\\/user0\\\/c...', 'files\\\/user0\\\/myC...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/DAV\\\/LazyOpsPlugin.php(124): Sabre\\\\DAV\\\\Server->emit('method:MOVE', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/DAV\\\/LazyOpsPlugin.php(106): OCA\\\\DAV\\\\DAV\\\\LazyOpsPlugin->afterResponse(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Shutdown\\\/ShutDownManager.php(61): OCA\\\\DAV\\\\DAV\\\\LazyOpsPlugin->OCA\\\\DAV\\\\DAV\\\\{closure}()\\n#10 [internal function]: OC\\\\Shutdown\\\\ShutDownManager->run()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":654}"}
      
      Failed asserting that 'no app in context' contains "files_antivirus".
And as "user0" file "/myChunkedFile.txt" should not exist # FeatureContext::asFileOrFolderShouldNotExist()
```

**Comment by phil-davis** [comment]
Fixed by #296
